#!/usr/bin/env bash

app=${1:-local-user-authenticator}
tag="${2:-latest}"

if [ "${app}" = "local-user-authenticator" ]; then
  mkdir -p target/charts
  cp -r charts/pinniped-local-user-authenticator target/charts
  helm template \
    --values source/pinniped-local-user-authenticator/values-lit.yaml \
    --set image.version=${tag} \
    --output-dir target/lit \
    --namespace local-user-authenticator target/charts/pinniped-local-user-authenticator
fi

if [ "${app}" = "pinniped-supervisor" ]; then
  mkdir -p target/charts
  cp -r charts/pinniped-supervisor target/charts
  cp target/pinniped-supervisor/crds.helm/*.yaml target/charts/pinniped-supervisor/templates
  helm template \
    --values source/pinniped-supervisor/values-lit.yaml \
    --set image.version=${tag} \
    --output-dir target/lit \
    --namespace supervisor target/charts/pinniped-supervisor
fi

if [ "${app}" = "pinniped-concierge" ]; then
  discovery_url="$(TERM=dumb kubectl cluster-info | awk '/master|control plane/ {print $NF}')"
  mkdir -p target/charts
  cp -r charts/pinniped-concierge target/charts
  cp target/pinniped-concierge/crds.helm/*.yaml target/charts/pinniped-concierge/templates
  helm --debug template \
    --values source/pinniped-concierge/values-lit.yaml \
    --set image.version=${tag} \
    --set config.discovery.url=${discovery_url} \
    --set config.logLevel="debug" \
    --output-dir target/lit \
    --namespace concierge target/charts/pinniped-concierge
fi
