#!/usr/bin/env bash

version="$(cat VERSION | tr -d '\n')"
version=$((version+1))
echo ${version} > VERSION
git tag "0.0.${version}"
git push --tags
./generate-charts
git add .
git commit -m "Update charts"
git push
