#!/usr/bin/env bash

version="$(cat VERSION | tr -d '\n')"
version=$((version+1))
echo ${version} > VERSION
./generate-charts
git add .
git commit -m "Update charts"
git tag ${version}
git push && git push --tags
