apiVersion: v1
kind: ConfigMap
metadata:
  name: pinniped-supervisor-static-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "labels" .Values }}
data:
  pinniped.yaml: |
    apiGroupSuffix: pinniped.dev
    names:
      defaultTLSCertificateSecret: pinniped-supervisor-default-tls-certificate
    labels:
      {{ include "labels6" .Values }}
