apiVersion: v1
kind: ConfigMap
metadata:
  name: pinniped-supervisor-static-config
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: pinniped-supervisor
data:
  pinniped.yaml: |
    apiGroupSuffix: pinniped.dev
    names:
      defaultTLSCertificateSecret: pinniped-supervisor-default-tls-certificate
    labels:
      app: pinniped-supervisor
