{{- if .Values.image.credentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.image.credentials.secretName }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}