kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinniped-supervisor
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "labels" .Values }}
subjects:
  - kind: ServiceAccount
    name: pinniped-supervisor
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pinniped-supervisor
  apiGroup: rbac.authorization.k8s.io
