{{- if .Values.service.test }}
apiVersion: v1
kind: Service
metadata:
  name: pinniped-supervisor-clusterip
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: pinniped-supervisor
  annotations:
    kapp.k14s.io/disable-default-label-scoping-rules: ""
spec:
  type: ClusterIP
  selector:
    deployment.pinniped.dev: supervisor
  ports:
    - name: {{ .Values.service.clusterIP.name }}
      protocol: {{ .Values.service.clusterIP.protocol }}
      port: {{ .Values.service.clusterIP.targetPort }}
      targetPort: {{ .Values.service.clusterIP.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: pinniped-supervisor-nodeport
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: pinniped-supervisor
  annotations:
    kapp.k14s.io/disable-default-label-scoping-rules: ""
spec:
  type: NodePort
  selector:
    deployment.pinniped.dev: supervisor
  ports:
    - name: {{ .Values.service.nodePort.name }}
      protocol: {{ .Values.service.nodePort.protocol }}
      port: {{ .Values.service.nodePort.targetPort }}
      targetPort: {{ .Values.service.nodePort.port }}
{{- end }}
