apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-user-authenticator
  namespace: {{ .Release.Namespace }}
  labels:
    app: local-user-authenticator
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: local-user-authenticator
  template:
    metadata:
      labels: {{ include "labels" .Values | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
      serviceAccountName: local-user-authenticator
      containers:
        - name: local-user-authenticator
          image: {{ template "image" .Values.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - local-user-authenticator
