kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: local-user-authenticator
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "labels" .Values }}
subjects:
  - kind: ServiceAccount
    name: local-user-authenticator
    namespace: local-user-authenticator
roleRef:
  kind: Role
  name: local-user-authenticator
  apiGroup: rbac.authorization.k8s.io
