apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: local-user-authenticator
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "labels" .Values }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
