apiVersion: v1
kind: Service
metadata:
  name: local-user-authenticator
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "labels" .Values }}
  annotations:
    kapp.k14s.io/disable-default-label-scoping-rules: ""
spec:
  type: ClusterIP
  selector:
    app: local-user-authenticator
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
