kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinniped-concierge-impersonation-proxy
  labels:
    {{ include "labels" .Values }}
subjects:
  - kind: ServiceAccount
    name: pinniped-concierge-impersonation-proxy
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: pinniped-concierge-impersonation-proxy
  apiGroup: rbac.authorization.k8s.io
