kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinniped-concierge-aggregated-api-server
  labels:
    {{ include "labels" .Values }}
subjects:
  - kind: ServiceAccount
    name: pinniped-concierge
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: pinniped-concierge-aggregated-api-server
  apiGroup: rbac.authorization.k8s.io
