kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinniped-concierge
  labels: {{ include "labels" .Values | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: pinniped-concierge
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
