apiVersion: config.concierge.pinniped.dev/v1alpha1
kind: CredentialIssuer
metadata:
  name: pinniped-concierge-config
  labels: {{ include "labels" .Values | nindent 4 }}
spec:
  impersonationProxy:
    mode: {{ .Values.credentialIssuer.impersonationProxy.mode }}
    service:
      type: {{ .Values.credentialIssuer.impersonationProxy.service.type }}
      annotations: {{ include "nindent8" .Values.credentialIssuer.impersonationProxy.service.annotations }}
