kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinniped-concierge-aggregated-api-server
  namespace: {{ .Release.Namespace }}
  labels: {{ include "labels" .Values | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: pinniped-concierge
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: pinniped-concierge-aggregated-api-server
  apiGroup: rbac.authorization.k8s.io
