kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinniped-concierge-kube-cert-agent
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: pinniped-concierge
subjects:
  - kind: ServiceAccount
    name: pinniped-concierge-kube-cert-agent
    namespace: '{{ .Release.Namespace }}'
roleRef:
  kind: Role
  name: pinniped-concierge-kube-cert-agent
  apiGroup: rbac.authorization.k8s.io
