apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinniped-concierge-impersonation-proxy
  namespace: {{ .Release.Namespace }}
  labels: {{ include "labels" .Values | nindent 4 }}
  annotations:
    kapp.k14s.io/change-group: impersonation-proxy.concierge.pinniped.dev/serviceaccount
secrets:
  - name: pinniped-concierge-impersonation-proxy
