apiVersion: v1
kind: Service
metadata:
  name: pinniped-concierge-proxy
  namespace: '{{ .Release.Namespace }}'
  labels:
    app: pinniped-concierge
  annotations:
    kapp.k14s.io/disable-default-label-scoping-rules: ""
spec:
  type: ClusterIP
  selector:
    deployment.pinniped.dev: concierge
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8444
