# -------------------------------------------------------------------------------------------------
# Concierge
# -------------------------------------------------------------------------------------------------

replicas: 2

# How to process this in the same way as ytt
customLabels: {}

# https://blog.andyserver.com/2021/09/adding-image-digest-references-to-your-helm-charts/
image:
  registry: "projects.registry.vmware.com"
  repository: "pinniped/pinniped-server"
  version: "latest"
  #version: "sha256:f3c4fdfd3ef865d4b97a1fd295d94acc3f0c654c46b6f27ffad5cf80216903c8"
  pullPolicy: IfNotPresent
  credentials: 
    enabled: false
    username: ""
    password: ""
    email: ""
    secretName: "regcred"

nameOverride: ""
fullnameOverride: ""

# This is all deployment stuff

securityContext:
  runAsUser: 65532
  runAsGroup: 65532

# pinniped.yaml config
config:
  api:
    servingCertificate:
      durationSeconds: 2592000
      renewBeforeSeconds: 2160000
  apiGroupSuffix: pinniped.dev

impersonationProxy:
  mode: auto
  externalEndpoint: ""
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "4000"
    loadBalancerIp: ""

# Set the standard golang HTTPS_PROXY and NO_PROXY environment variables on the Concierge containers.
# These will be used when the Concierge makes backend-to-backend calls to authenticators using HTTPS,
# e.g. when the Concierge fetches discovery documents, JWKS keys, and POSTs to token webhooks.
# The Concierge never makes insecure HTTP calls, so there is no reason to set HTTP_PROXY.
# Optional.
#env:
#  HTTPS_PROXY: http://proxy.example.com
#  NO_PROXY: "$(KUBERNETES_SERVICE_HOST),169.254.169.254,127.0.0.1,localhost,.svc,.cluster.local" #! do not proxy Kubernetes endpoints